# Generated by Django 2.1.2 on 2018-10-23 17:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the class', max_length=1000)),
                ('exams', models.BooleanField()),
                ('attendance', models.BooleanField()),
                ('textbooks', models.TextField(help_text='Enter the textbooks needed for the class', max_length=1000)),
                ('class_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular class across the website', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Enter a brief comment about the class.', max_length=1000)),
                ('rating', models.CharField(help_text='Give a rating from 1 to 5', max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spew.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('contact', models.TextField(help_text='Enter a brief description of the class', max_length=1000)),
                ('office', models.CharField(max_length=100)),
                ('course', models.ManyToManyField(help_text='Select a class this professor teaches', to='spew.Class')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('user_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular user', primary_key=True, serialize=False)),
                ('favorite_classes', models.ManyToManyField(help_text='Select the classes this user favorites', to='spew.Class')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spew.User'),
        ),
    ]
