# Generated by Django 2.1.2 on 2018-11-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SpewUser',
        ),
    ]
