# Generated by Django 2.1.2 on 2018-10-30 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0003_auto_20181025_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.UUIDField(default=uuid.uuid1, help_text='Unique ID for this particular class across the website', primary_key=True, serialize=False),
        ),
    ]
