# Generated by Django 2.1.2 on 2018-10-30 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0004_auto_20181030_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Enter a class subject (e.g. Computer Science)', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular class across the website', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spew.Subject'),
        ),
    ]
