# Generated by Django 2.1.2 on 2018-11-25 08:47

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('spew', '0004_auto_20181125_0526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpewUser',
            new_name='User',
        ),
    ]
