# Generated by Django 2.1.2 on 2018-10-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0006_auto_20181031_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default='404', max_length=100),
        ),
    ]
