# Generated by Django 2.1.2 on 2018-10-31 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0007_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(default=uuid.uuid1, help_text='Unique ID for this particular class across the website', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
