# Generated by Django 2.1.2 on 2018-11-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0007_auto_20181125_0856'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
