# Generated by Django 2.1.2 on 2018-10-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0008_auto_20181031_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='related_class',
            field=models.ManyToManyField(help_text='Select a class that is related to this one', related_name='_class_related_class_+', to='spew.Class'),
        ),
    ]
