# Generated by Django 2.1.2 on 2018-11-26 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spew', '0008_auto_20181125_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('concentration', models.CharField(default='NA', max_length=100)),
                ('bio', models.TextField(default='', help_text='Enter a bio for this user', max_length=1000)),
                ('grad_year', models.CharField(default='2020', max_length=100)),
                ('num_classes_taken', models.TextField(default='', help_text='# of classes taken by this user', max_length=1000)),
                ('num_liked_reviews', models.TextField(default='', help_text='# of reviews this user liked', max_length=1000)),
                ('student_id', models.CharField(default=uuid.uuid4, help_text='Unique ID for this particular user', max_length=1000, primary_key=True, serialize=False)),
                ('current_courses', models.ManyToManyField(help_text='Select the classes this user is currently taking', related_name='current_courses', to='spew.Class')),
                ('fav_courses', models.ManyToManyField(help_text='Select the classes this user favorites', related_name='fav_courses', to='spew.Class')),
                ('major', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='spew.Subject')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fav_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spew.Student'),
        ),
    ]
