# Generated by Django 2.1.2 on 2018-10-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0009_class_related_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='related_class',
        ),
        migrations.AddField(
            model_name='class',
            name='related_classes',
            field=models.ManyToManyField(help_text='Select a class that is related to this one', related_name='_class_related_classes_+', to='spew.Class'),
        ),
    ]
