# Generated by Django 2.1.2 on 2018-11-27 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0010_auto_20181127_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': (('can_add_feedback', 'Can add feedback'),)},
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
