# Generated by Django 2.1.2 on 2018-11-27 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0011_auto_20181127_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foobar', to=settings.AUTH_USER_MODEL),
        ),
    ]
