# Generated by Django 2.1.2 on 2018-11-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0011_class_num_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='attendance',
            field=models.TextField(help_text='Is attendance taken at this class?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='class',
            name='exams',
            field=models.TextField(help_text='Does this class have exams?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='class',
            name='num_credits',
            field=models.TextField(help_text='Enter a the number of credits this class fulfills', max_length=1000),
        ),
        migrations.AlterField(
            model_name='class',
            name='textbooks',
            field=models.TextField(help_text='Does this class require textbooks?', max_length=1000),
        ),
    ]
