# Generated by Django 2.1.2 on 2018-11-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0012_auto_20181101_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_feedback',
            field=models.ManyToManyField(help_text='Provide feedback for this class', to='spew.Feedback'),
        ),
    ]
