# Generated by Django 2.1.2 on 2018-11-05 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0013_class_class_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.uuid1, help_text='Unique ID for this particular class across the website', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
