# Generated by Django 2.1.2 on 2018-12-03 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spew', '0013_auto_20181127_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spew.Feedback')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='current_courses',
            field=models.ManyToManyField(blank=True, help_text='Select the classes this user is currently taking', related_name='current_courses', to='spew.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fav_courses',
            field=models.ManyToManyField(blank=True, help_text='Select the classes this user favorites', related_name='fav_courses', to='spew.Class'),
        ),
    ]
