# Generated by Django 2.1.2 on 2018-11-06 00:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0014_auto_20181105_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', help_text='Enter a bio for this user', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='grad_year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, help_text='Unique ID for this particular user', max_length=100, primary_key=True, serialize=False),
        ),
    ]
