# Generated by Django 2.1.2 on 2018-11-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0015_auto_20181106_0010'),
        ('spew', '0015_auto_20181105_1917'),
    ]

    operations = [
    ]
