# Generated by Django 2.1.2 on 2018-11-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0017_auto_20181106_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_courses',
            field=models.ManyToManyField(help_text='Select the classes this user is currently taking', related_name='current_courses', to='spew.Class'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_courses',
            field=models.ManyToManyField(help_text='Select the classes this user favorites', related_name='fav_courses', to='spew.Class'),
        ),
    ]
