# Generated by Django 2.1.2 on 2018-11-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0020_user_current_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_courses',
        ),
    ]
