# Generated by Django 2.1.2 on 2018-11-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0023_auto_20181106_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_courses',
        ),
    ]
