# Generated by Django 2.1.2 on 2018-11-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0024_remove_user_current_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_courses',
            field=models.ManyToManyField(help_text='Select the classes this user is currently taking', related_name='current_courses', to='spew.Class'),
        ),
    ]
