# Generated by Django 2.1.2 on 2018-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0025_user_current_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='concentration',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
