# Generated by Django 2.1.2 on 2018-11-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0026_user_concentration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_classes_taken',
            field=models.TextField(default='', help_text='# of classes taken by this user', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='num_liked_reviews',
            field=models.TextField(default='', help_text='# of reviews this user liked', max_length=1000),
        ),
    ]
